# Generated by Django 4.1.2 on 2022-10-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_druzyna_osoba_kraj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='kraj',
            new_name='druzyna',
        ),
    ]
