# Generated by Django 4.1.3 on 2022-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.CharField(choices=[('1', 'styczeń'), ('2', 'luty'), ('3', 'marzec'), ('4', 'kwiecień'), ('5', 'maj'), ('6', 'czerwiec'), ('7', 'lipiec'), ('8', 'sierpień'), ('9', 'wrzesień'), ('10', 'październik'), ('11', 'listopad'), ('12', 'grudzień')], default=11, max_length=255),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.CharField(choices=[('1', 'styczeń'), ('2', 'luty'), ('3', 'marzec'), ('4', 'kwiecień'), ('5', 'maj'), ('6', 'czerwiec'), ('7', 'lipiec'), ('8', 'sierpień'), ('9', 'wrzesień'), ('10', 'październik'), ('11', 'listopad'), ('12', 'grudzień')], default=11, max_length=255),
        ),
    ]
