# Generated by Django 4.1.3 on 2022-11-11 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_osoba_miesiac_dodania_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Tylko litery')]),
        ),
    ]
