# Generated by Django 4.1.2 on 2022-10-26 10:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('kraj', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Tylko duże litery')])),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('miesiac_urodzenia', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=(1, 'Styczeń'))),
                ('data_dodania', models.DateField(default=datetime.datetime.now)),
                ('druzyna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osoby.druzyna')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
    ]
